spring:
  application:
    name: treeco
  datasource:
    # Los valores entre ${} los leerá del sistema (Render o tu PC)
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 'update' crea las tablas automáticamente en Supabase al arrancar
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Esto es importante para Supabase/Postgres
        format_sql: true

server:
  # Puerto por defecto de Spring Boot
  port: 8080
